name: bluefin-developers
description: My personal development Bluefin image.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: script
    snippets:
      - curl -fsSL https://aaddrick.github.io/claude-desktop-debian/rpm/claude-desktop.repo -o /etc/yum.repos.d/claude-desktop.repo
      - dnf copr enable -y alternateved/keyd

      - >
        dnf install -y
        waydroid
        gh
        claude-desktop
        tor
        obfs4
        earlyoom
        tailscale
        ripgrep
        nix
        sysstat
        wtype
        keyd
        ydotool
        wl-clipboard
        vulkan-loader
        playerctl
        privoxy
        mutter-devel
        gnome-shell-devel
        gjs-devel
        meson
        ninja-build
        sysprof
        gtk4-devel
        libadwaita-devel

      - systemctl enable keyd.service
      - systemctl enable ydotool.service || true

  - type: signing
