name: bluefin-developers
description: My personal development Bluefin image.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest
modules:
  - type: script
    snippets:
      - dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release terra-gpg-keys
      - curl -fsSL https://aaddrick.github.io/claude-desktop-debian/rpm/claude-desktop.repo -o /etc/yum.repos.d/claude-desktop.repo
      - dnf copr enable -y alternateved/keyd
      - wget "https://repo.protonvpn.com/fedora-$(cat /etc/fedora-release | cut -d' ' -f 3)-stable/protonvpn-stable-release/protonvpn-stable-release-1.0.4-1.noarch.rpm"
      - sudo dnf install -y ./protonvpn-stable-release-1.0.4-1.noarch.rpm && sudo dnf check-update --refresh 
      - sudo dnf install -y proton-vpn-cli
      - >
        dnf install -y
        node
        npm
        waydroid
        gh
        claude-desktop
        tor
        obfs4
        earlyoom
        tailscale
        ripgrep
        nix
        sysstat
        wtype
        keyd
        ydotool
        wl-clipboard
        vulkan-loader
        playerctl
        privoxy
        mutter-devel
        gjs-devel
        meson
        ninja-build
        sysprof
        gtk4-devel
        libadwaita-devel
        duo_unix
        gstreamer1-plugin-gtk4
        hcitool
      - systemctl enable keyd.service
      - systemctl enable ydotool.service || true
      - npx playwright install
  - type: signing
