name: bluefin-developers
description: My personal development Bluefin image.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: beta
modules:
  - type: script
    snippets:
      - "curl -fsSL https://aaddrick.github.io/claude-desktop-debian/rpm/claude-desktop.repo -o /etc/yum.repos.d/claude-desktop.repo"
      - "curl https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo | sudo tee /etc/yum.repos.d/cloudflare-warp.repo"
      - "dnf install -y waydroid gh claude-desktop tor obfs4 earlyoom tailscale ripgrep nix cloudflare-warp"
  - type: signing
